import { Product } from '@/types/product'

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'Apple iPhone 15 Pro',
    description: 'Latest iPhone with A17 Pro chip, titanium design, and advanced camera system. Perfect for photography and performance.',
    price: 999,
    category: 'Electronics',
    brand: 'Apple',
    imageUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400',
    tags: ['smartphone', 'ios', 'camera', 'premium'],
    rating: 4.8,
    reviewCount: 1247,
    inStock: true,
    createdAt: '2024-01-15T00:00:00Z'
  },
  {
    id: '2',
    name: 'Nike Air Max 270 Running Shoes',
    description: 'Comfortable running shoes with Air Max cushioning technology. Great for daily runs and casual wear.',
    price: 150,
    category: 'Sports & Outdoors',
    brand: 'Nike',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    tags: ['running', 'shoes', 'comfortable', 'athletic'],
    rating: 4.5,
    reviewCount: 892,
    inStock: true,
    createdAt: '2024-01-10T00:00:00Z'
  },
  {
    id: '3',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    description: 'Industry-leading noise canceling wireless headphones with premium sound quality and all-day comfort.',
    price: 399,
    category: 'Electronics',
    brand: 'Sony',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
    tags: ['headphones', 'wireless', 'noise-canceling', 'premium'],
    rating: 4.7,
    reviewCount: 2156,
    inStock: true,
    createdAt: '2024-01-08T00:00:00Z'
  },
  {
    id: '4',
    name: 'Organic Cotton Basic T-Shirt',
    description: 'Soft, breathable organic cotton t-shirt perfect for everyday wear. Available in multiple colors.',
    price: 25,
    category: 'Clothing',
    brand: 'EcoWear',
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
    tags: ['t-shirt', 'organic', 'cotton', 'basic'],
    rating: 4.3,
    reviewCount: 456,
    inStock: true,
    createdAt: '2024-01-12T00:00:00Z'
  },
  {
    id: '5',
    name: 'Dell XPS 13 Laptop',
    description: 'Powerful ultrabook with Intel Core i7 processor, 16GB RAM, and stunning InfinityEdge display. Perfect for programming and productivity.',
    price: 1299,
    category: 'Electronics',
    brand: 'Dell',
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400',
    tags: ['laptop', 'programming', 'ultrabook', 'productivity'],
    rating: 4.6,
    reviewCount: 743,
    inStock: true,
    createdAt: '2024-01-05T00:00:00Z'
  },
  {
    id: '6',
    name: 'Adidas Ultraboost 22 Running Shoes',
    description: 'Premium running shoes with Boost midsole technology for energy return and comfort during long runs.',
    price: 180,
    category: 'Sports & Outdoors',
    brand: 'Adidas',
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400',
    tags: ['running', 'boost', 'comfortable', 'premium'],
    rating: 4.4,
    reviewCount: 1089,
    inStock: false,
    createdAt: '2024-01-03T00:00:00Z'
  },
  {
    id: '7',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Flagship Android smartphone with S Pen, 200MP camera, and AI-powered features for productivity and creativity.',
    price: 1199,
    category: 'Electronics',
    brand: 'Samsung',
    imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400',
    tags: ['smartphone', 'android', 'camera', 's-pen'],
    rating: 4.5,
    reviewCount: 934,
    inStock: true,
    createdAt: '2024-01-20T00:00:00Z'
  },
  {
    id: '8',
    name: 'Levi\'s 501 Original Jeans',
    description: 'Classic straight-fit jeans made from premium denim. Timeless style that never goes out of fashion.',
    price: 89,
    category: 'Clothing',
    brand: 'Levis',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400',
    tags: ['jeans', 'denim', 'classic', 'straight-fit'],
    rating: 4.2,
    reviewCount: 2847,
    inStock: true,
    createdAt: '2024-01-18T00:00:00Z'
  },
  {
    id: '9',
    name: 'Canon EOS R5 Mirrorless Camera',
    description: 'Professional mirrorless camera with 45MP sensor and 8K video recording capabilities. Perfect for professional photography.',
    price: 3899,
    category: 'Electronics',
    brand: 'Canon',
    imageUrl: 'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=400',
    tags: ['camera', 'mirrorless', 'photography', 'professional'],
    rating: 4.9,
    reviewCount: 567,
    inStock: true,
    createdAt: '2024-01-25T00:00:00Z'
  },
  {
    id: '10',
    name: 'Patagonia Houdini Jacket',
    description: 'Lightweight windbreaker jacket perfect for outdoor activities. Packable and weather-resistant.',
    price: 129,
    category: 'Clothing',
    brand: 'Patagonia',
    imageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400',
    tags: ['jacket', 'windbreaker', 'outdoor', 'lightweight'],
    rating: 4.6,
    reviewCount: 378,
    inStock: true,
    createdAt: '2024-01-22T00:00:00Z'
  },
  {
    id: '11',
    name: 'HP Spectre x360 2-in-1 Laptop',
    description: 'Versatile 2-in-1 laptop with touchscreen display and stylus support. Great for creative work and presentations.',
    price: 1099,
    category: 'Electronics',
    brand: 'HP',
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400',
    tags: ['laptop', '2-in-1', 'touchscreen', 'creative'],
    rating: 4.3,
    reviewCount: 623,
    inStock: true,
    createdAt: '2024-01-14T00:00:00Z'
  },
  {
    id: '12',
    name: 'Apple AirPods Pro (2nd Generation)',
    description: 'Premium wireless earbuds with active noise cancellation and spatial audio technology.',
    price: 249,
    category: 'Electronics',
    brand: 'Apple',
    imageUrl: 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=400',
    tags: ['earbuds', 'wireless', 'noise-canceling', 'apple'],
    rating: 4.7,
    reviewCount: 1456,
    inStock: true,
    createdAt: '2024-01-30T00:00:00Z'
  },
  {
    id: '13',
    name: 'Under Armour HeatGear T-Shirt',
    description: 'Moisture-wicking athletic t-shirt designed for intense workouts and hot weather training.',
    price: 35,
    category: 'Sports & Outdoors',
    brand: 'Under Armour',
    imageUrl: 'https://images.unsplash.com/photo-1583743814966-8936f37f8c16?w=400',
    tags: ['athletic', 'moisture-wicking', 't-shirt', 'workout'],
    rating: 4.1,
    reviewCount: 789,
    inStock: true,
    createdAt: '2024-02-01T00:00:00Z'
  },
  {
    id: '14',
    name: 'Amazon Echo Dot (5th Gen)',
    description: 'Smart speaker with Alexa voice assistant. Control smart home devices and play music with voice commands.',
    price: 49,
    category: 'Electronics',
    brand: 'Amazon',
    imageUrl: 'https://images.unsplash.com/photo-1543512214-318c7553f230?w=400',
    tags: ['smart-speaker', 'alexa', 'voice-assistant', 'smart-home'],
    rating: 4.4,
    reviewCount: 12456,
    inStock: true,
    createdAt: '2024-02-03T00:00:00Z'
  },
  {
    id: '15',
    name: 'Allbirds Tree Runners',
    description: 'Sustainable running shoes made from eucalyptus tree fiber. Comfortable and eco-friendly footwear.',
    price: 95,
    category: 'Sports & Outdoors',
    brand: 'Allbirds',
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400',
    tags: ['sustainable', 'running', 'eco-friendly', 'comfortable'],
    rating: 4.2,
    reviewCount: 567,
    inStock: true,
    createdAt: '2024-02-05T00:00:00Z'
  }
]